//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id { get; set; }
        public int id_compras { get; set; }
        public int id_producto { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
